name: oi-bot-env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - requests
  - aiohttp==3.9.5
  - pandas
  - python-dotenv
  - schedule
  - pandas-ta
  - certifi
  - aiohttp-socks==0.8.4
  - pytz
